### PR TITLE
tagged fonts as family or multi-weight

### PR DESCRIPTION
**Pull request by geoffyuen**
- tagged a font set as 'family' if it has at least 1 regular, 1 bold, 1 italic and 1 bold-italic
- tagged a font set as 'multi-weight' if it has more than one weight

Please excuse me if I've done this pull request incorrectly. My git knowledge is pretty poor.

### CODE REVIEW

**Comment by davelab6** [comment]
> tagged a font set as 'family' if it has at least 1 regular, 1 bold, 1 italic and 1 bold-italic

I think `office-family` would be better, since many fonts from many foundries are families when they are 2+ styles, maybe without italics, eg light and regular

**Comment by katydecorah** [comment]
@geoffyuen No worries - you did this pull request beautifully!

The only question I have: are the "family" and "multi-weight" tags ones that you would use? Most tags refer to the style of the font, so I want to be sure this tag holds utility. I suppose I'm coming up short for a personal reason for wanting search for fonts with "multi-weight." But if these are tags that are useful to you, then I'm happy to merge.

**Comment by geoffyuen** [comment]
@katydecorah I guess didn't understand that the tags are for font styles (I'm a notorious skimmer). The tags that I created are more for finding "complete" font sets. I build sites around Wordpress where my clients will want to style text using bold/strong or em/italics so being able to choose font families where there's at least these styles would be handy. If this is not really the scope of this project then by all means please ignore.

**Comment by katydecorah** [comment]
@geoffyuen Thanks for the background. I had a similar thought process when wanting to add subsets as tags (#4). I found that the tags weren't very intuitive and started to dilute the tag pool. Ideally, yes, I think tags based on style is this project's goal... but this can be adapted.

**Let's leave the PR open and if other people +1 this thread, then we'll add it!**

**Comment by alienresident** [comment]
**+1**   

Open Source fonts tend not to have additional styles. So I think it's important to tag them when they do!

For headings or display text:  I often look to see if there's a **bold** version
For body text: I look for fonts that have **bold**, _italic_, and **_bold-italic**_. 

If I am going with one font for a whole site (headings and body text) I'll want to find a "multi-weight" font.   

I also look for fonts that have a serif or sans serif counterpart. I wonder if we could use the tag "family: extended".  i.e. **Droid Sans** is _related_ of **Droid Serif**;

| Tag | Criteria |
| --- | --- |
| `"family: small"` | at least 1 additional style |
| `"family: medium"` | **bold**, _italic_, and **_bold-italic**_ |
| `"family: large"` | multi-weight |
| `"family: extended"` | Counter parts in different styles |

I am proposing using the pattern `"family: xxxxx"` so they're all clustered together. 

Are you interested in tagging fonts' attributes? i.e. "large x-height" "tall ascenders"; and/or use cases? i.e. "print", "screen", "user interface"?

**Comment by katydecorah** [comment]
Really great input, it's got my wheels spinning. We can get all the variant data for each font from the Google Font API. I just did some fiddling and I was able to merge `families.json` and the Google Font API, so that the output in Font Library can contain data from both sources.

At the moment, each font will list the number of variants:

image

And right now, you can technically search for these variants by hitting the URL:

http://katydecorah.com/font-library/#/700italic/
http://katydecorah.com/font-library/#/100/
http://katydecorah.com/font-library/#/italic/

I haven't added them to the tag pool yet, I just want to play around and improve the code I've written.

**Comment by katydecorah** [comment]
Hey all, I wrenched on the code and made some major improvements. Not only can you filter by "tag" but also "category", "subset", and "variant". You can apply all 4 at once. Or just 1.

image

I think this covers finding different variants. Closing this PR because of these updated. Thanks for your feedback :heart:

**Pull request closed without merging**
