### PR TITLE
Update families.json

### PR DESCRIPTION
**Pull request by jeannie2**
Added tags for 7 fonts. Propose new tag "collegiate" for Alumni Sans Collegiate One

### CODE REVIEW

**Review by katydecorah — APPROVED** [review]
🌻 Thank you!

**Comment by jeannie2** [comment]
Thanks Katy, and Merry Christmas! 

By the way, I decided to enroll in a full-time coding bootcamp starting in January.

**Comment by katydecorah** [comment]
@jeannie2 Merry Christmas! Congratulations on starting at a bootcamp next month. I would love to hear how it goes!

**Comment by jeannie2** [comment]
Thanks Katy, your support means a lot. Will keep you posted

**Pull request merged**
