### PR TITLE
Update families.json

### PR DESCRIPTION
**Pull request by jeannie2**
added tags for 5 font families

### CODE REVIEW

**Review by katydecorah — APPROVED** [review]
🌷 Thank you!

**Comment by jeannie2** [comment]
Thanks Katy, and hope you're doing well. I saw the Font Library site has been updated - it's easier to find which fonts need tagging.  As for me, bootcamp ended well and so now beginning job search.

**Comment by katydecorah** [comment]
@jeannie2 Congratulations on finishing the bootcamp! 🎉 What type of roles are you looking for?

**Comment by jeannie2** [comment]
Thank you @katydecorah, it means a lot. We worked on 4 projects (my pinned repos) using various tools/technologies. I'm interested in junior-level full-stack web dev/SWE roles

**Pull request merged**
