### PR TITLE
Update families.json

### PR DESCRIPTION
**Pull request by jeannie2**
Tagged 6 fonts

### CODE REVIEW

**Review by katydecorah — COMMENTED** [review]
🍄

**Comment by jeannie2** [comment]
thanks Katy! I hope you're doing well.

By the way, would it be at all possible to ask a quick career advice-related question? If so, may I know which channel you prefer for communicating e.g. email address? Only if you have time and don't mind. Meanwhile, I'll be tagging more fonts for this week's PR :)

**Comment by katydecorah** [comment]
@jeannie2 Yes 😀 email works best: katydecorah@gmail.com

**Comment by jeannie2** [comment]
Thank you very much Katy, I wrote to you today (email from jnam820@gmail.com).

**Pull request merged**
